export enum ErrorTag {
  VALIDATION_FAILED = 'VALIDATION_FAILED', //400
  UNAUTHORIZED = 'UNAUTHORIZED', //401
  PERMISSION_DENIED = 'PERMISSION_DENIED', //403
  NOT_FOUND = 'NOT_FOUND', //404
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR', //500
  BAD_GATEWAY = 'BAD_GATEWAY', //502
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE', //503
}
