-- CreateTable
CREATE TABLE "Profiles" (
    "id" SERIAL NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT NOT NULL,
    "dateOfBirth" TIMESTAMP(3),
    "country" TEXT,
    "city" TEXT,
    "aboutMe" TEXT,
    "userId" INTEGER NOT NULL,

    CONSTRAINT "Profiles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Avatars" (
    "id" SERIAL NOT NULL,
    "originalUrl" TEXT NOT NULL,
    "smallUrl" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,
    "deletedAt" TIMESTAMPTZ,
    "profileId" INTEGER NOT NULL,

    CONSTRAINT "Avatars_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Countries" (
    "id" SERIAL NOT NULL,
    "name_ru" TEXT NOT NULL,
    "name_en" TEXT NOT NULL,

    CONSTRAINT "Countries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Cities" (
    "id" SERIAL NOT NULL,
    "name_ru" TEXT NOT NULL,
    "name_en" TEXT NOT NULL,
    "countryId" INTEGER NOT NULL,

    CONSTRAINT "Cities_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Profiles_userId_key" ON "Profiles"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "Avatars_profileId_key" ON "Avatars"("profileId");

-- CreateIndex
CREATE UNIQUE INDEX "Countries_name_ru_key" ON "Countries"("name_ru");

-- CreateIndex
CREATE UNIQUE INDEX "Countries_name_en_key" ON "Countries"("name_en");

-- AddForeignKey
ALTER TABLE "Profiles" ADD CONSTRAINT "Profiles_userId_fkey" FOREIGN KEY ("userId") REFERENCES "Users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Avatars" ADD CONSTRAINT "Avatars_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Cities" ADD CONSTRAINT "Cities_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "Countries"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

--InsertCountries
INSERT INTO "Countries" (id, name_ru, name_en) VALUES
(1, 'Россия', 'Russia'),
(2, 'США', 'United States'),
(3, 'Франция', 'France'),
(4, 'Германия', 'Germany'),
(5, 'Италия', 'Italy'),
(6, 'Испания', 'Spain'),
(7, 'Китай', 'China'),
(8, 'Япония', 'Japan'),
(9, 'Индия', 'India'),
(10, 'Бразилия', 'Brazil'),
(11, 'Канада', 'Canada'),
(12, 'Австралия', 'Australia'),
(13, 'Мексика', 'Mexico'),
(14, 'Великобритания', 'United Kingdom'),
(15, 'Новая Зеландия', 'New Zealand'),
(16, 'Южноафриканская Республика', 'South Africa'),
(17, 'Индонезия', 'Indonesia'),
(18, 'Аргентина', 'Argentina'),
(19, 'Турция', 'Turkey'),
(20, 'Норвегия', 'Norway'),
(21, 'Швеция', 'Sweden'),
(22, 'Дания', 'Denmark'),
(23, 'Финляндия', 'Finland'),
(24, 'Ирландия', 'Ireland'),
(25, 'Польша', 'Poland'),
(26, 'Чехия', 'Czech Republic'),
(27, 'Словакия', 'Slovakia'),
(28, 'Греция', 'Greece'),
(29, 'Португалия', 'Portugal'),
(30, 'Хорватия', 'Croatia'),
(31, 'Румыния', 'Romania'),
(32, 'Болгария', 'Bulgaria'),
(33, 'Сербия', 'Serbia'),
(34, 'Венгрия', 'Hungary'),
(35, 'Австрия', 'Austria'),
(36, 'Швейцария', 'Switzerland'),
(37, 'Беларусь', 'Belarus'),
(38, 'Украина', 'Ukraine'),
(39, 'Молдова', 'Moldova'),
(40, 'Казахстан', 'Kazakhstan'),
(41, 'Узбекистан', 'Uzbekistan'),
(42, 'Таджикистан', 'Tajikistan'),
(43, 'Кыргызстан', 'Kyrgyzstan'),
(44, 'Грузия', 'Georgia'),
(45, 'Армения', 'Armenia'),
(46, 'Азербайджан', 'Azerbaijan'),
(47, 'Сирия', 'Syria'),
(48, 'Ирак', 'Iraq'),
(49, 'Иран', 'Iran'),
(50, 'Израиль', 'Israel');

--InsertCities
INSERT INTO "Cities" (name_ru, name_en, "countryId") VALUES
('Москва', 'Moscow', 1),
('Санкт-Петербург', 'Saint Petersburg', 1),
('Новосибирск', 'Novosibirsk', 1),
('Екатеринбург', 'Yekaterinburg', 1),
('Казань', 'Kazan', 1),
('Вашингтон', 'Washington', 2),
('Нью-Йорк', 'New York', 2),
('Лос-Анджелес', 'Los Angeles', 2),
('Чикаго', 'Chicago', 2),
('Хьюстон', 'Houston', 2),
('Париж', 'Paris', 3),
('Марсель', 'Marseille', 3),
('Лион', 'Lyon', 3),
('Тулуза', 'Toulouse', 3),
('Ницца', 'Nice', 3),
('Берлин', 'Berlin', 4),
('Мюнхен', 'Munich', 4),
('Гамбург', 'Hamburg', 4),
('Кёльн', 'Cologne', 4),
('Франкфурт', 'Frankfurt', 4),
('Рим', 'Rome', 5),
('Милан', 'Milan', 5),
('Неаполь', 'Naples', 5),
('Турин', 'Turin', 5),
('Флоренция', 'Florence', 5),
('Мадрид', 'Madrid', 6),
('Барселона', 'Barcelona', 6),
('Валенсия', 'Valencia', 6),
('Севилья', 'Seville', 6),
('Бильбао', 'Bilbao', 6),
('Пекин', 'Beijing', 7),
('Шанхай', 'Shanghai', 7),
('Гуанчжоу', 'Guangzhou', 7),
('Шэньчжэнь', 'Shenzhen', 7),
('Чунцин', 'Chongqing', 7),
('Токио', 'Tokyo', 8),
('Осака', 'Osaka', 8),
('Нагоя', 'Nagoya', 8),
('Саппоро', 'Sapporo', 8),
('Киото', 'Kyoto', 8),
('Нью-Дели', 'New Delhi', 9),
('Мумбаи', 'Mumbai', 9),
('Бангалор', 'Bangalore', 9),
('Калькутта', 'Kolkata', 9),
('Ченнай', 'Chennai', 9),
('Бразилиа', 'Brasília', 10),
('Сан-Паулу', 'São Paulo', 10),
('Рио-де-Жанейро', 'Rio de Janeiro', 10),
('Салвадор', 'Salvador', 10),
('Форталеза', 'Fortaleza', 10),
('Оттава', 'Ottawa', 11),
('Торонто', 'Toronto', 11),
('Ванкувер', 'Vancouver', 11),
('Монреаль', 'Montreal', 11),
('Калгари', 'Calgary', 11),
('Канберра', 'Canberra', 12),
('Сидней', 'Sydney', 12),
('Мельбурн', 'Melbourne', 12),
('Брисбен', 'Brisbane', 12),
('Перт', 'Perth', 12),
('Мехико', 'Mexico City', 13),
('Гвадалахара', 'Guadalajara', 13),
('Монтеррей', 'Monterrey', 13),
('Пуэбла', 'Puebla', 13),
('Тихуана', 'Tijuana', 13),
('Лондон', 'London', 14),
('Бирмингем', 'Birmingham', 14),
('Манчестер', 'Manchester', 14),
('Глазго', 'Glasgow', 14),
('Ливерпуль', 'Liverpool', 14),
('Окленд', 'Auckland', 15),
('Веллингтон', 'Wellington', 15),
('Кристчurch', 'Christchurch', 15),
('Гамильтон', 'Hamilton', 15),
('Тауранга', 'Tauranga', 15),
('Пертория', 'Pretoria', 16),
('Кейптаун', 'Cape Town', 16),
('Дурбан', 'Durban', 16),
('Йоханнесбург', 'Johannesburg', 16),
('Порт-Элизабет', 'Port Elizabeth', 16),
('Джакарта', 'Jakarta', 17),
('Сурабая', 'Surabaya', 17),
('Бандунг', 'Bandung', 17),
('Медан', 'Medan', 17),
('Семаранг', 'Semarang', 17),
('Буэнос-Айрес', 'Buenos Aires', 18),
('Кордоба', 'Córdoba', 18),
('Росарио', 'Rosario', 18),
('Ла-Плата', 'La Plata', 18),
('Мендоса', 'Mendoza', 18),
('Анкара', 'Ankara', 19),
('Стамбул', 'Istanbul', 19),
('Измир', 'Izmir', 19),
('Бурса', 'Bursa', 19),
('Анталья', 'Antalya', 19),
('Осло', 'Oslo', 20),
('Берген', 'Bergen', 20),
('Ставангер', 'Stavanger', 20),
('Драммен', 'Drammen', 20),
('Трондхейм', 'Trondheim', 20),
('Стокгольм', 'Stockholm', 21),
('Гётеборг', 'Gothenburg', 21),
('Мальмё', 'Malmö', 21),
('Уппсала', 'Uppsala', 21),
('Вестерас', 'Västerås', 21),
('Копенгаген', 'Copenhagen', 22),
('Ольборг', 'Aalborg', 22),
('Аархус', 'Aarhus', 22),
('Роскилле', 'Roskilde', 22),
('Хернинг', 'Herning', 22),
('Хельсинки', 'Helsinki', 23),
('Эспоо', 'Espoo', 23),
('Тампере', 'Tampere', 23),
('Вантаа', 'Vantaa', 23),
('Оулу', 'Oulu', 23),
('Дублин', 'Dublin', 24),
('Корк', 'Cork', 24),
('Галвей', 'Galway', 24),
('Лимерик', 'Limerick', 24),
('Ватерфорд', 'Waterford', 24),
('Варшава', 'Warsaw', 25),
('Краков', 'Kraków', 25),
('Вроцлав', 'Wrocław', 25),
('Лодзь', 'Łódź', 25),
('Гданьск', 'Gdańsk', 25),
('Прага', 'Prague', 26),
('Брно', 'Brno', 26),
('Острава', 'Ostrava', 26),
('Плзень', 'Plzeň', 26),
('Либерец', 'Liberec', 26),
('Братислава', 'Bratislava', 27),
('Кошице', 'Košice', 27),
('Прешов', 'Prešov', 27),
('Нитра', 'Nitra', 27),
('Тренчин', 'Trenčín', 27),
('Афины', 'Athens', 28),
('Салоники', 'Thessaloniki', 28),
('Патры', 'Patras', 28),
('Ираклион', 'Heraklion', 28),
('Кавала', 'Kavala', 28),
('Лиссабон', 'Lisbon', 29),
('Порту', 'Porto', 29),
('Коимбра', 'Coimbra', 29),
('Брага', 'Braga', 29),
('Авейру', 'Aveiro', 29),
('Загреб', 'Zagreb', 30),
('Сплит', 'Split', 30),
('Риека', 'Rijeka', 30),
('Осиек', 'Osijek', 30),
('Дубровник', 'Dubrovnik', 30),
('Бухарест', 'Bucharest', 31),
('Клуж-Напока', 'Cluj-Napoca', 31),
('Тимишоара', 'Timișoara', 31),
('Яссы', 'Iași', 31),
('Брашов', 'Brașov', 31),
('София', 'Sofia', 32),
('Пловдив', 'Plovdiv', 32),
('Варна', 'Varna', 32),
('Бургас', 'Burgas', 32),
('Русе', 'Ruse', 32),
('Белград', 'Belgrade', 33),
('Нови-Сад', 'Novi Sad', 33),
('Ниш', 'Niš', 33),
('Крагуевац', 'Kragujevac', 33),
('Суботица', 'Subotica', 33),
('Будапешт', 'Budapest', 34),
('Дебрецен', 'Debrecen', 34),
('Сегед', 'Szeged', 34),
('Мишкольц', 'Miskolc', 34),
('Печ', 'Pécs', 34),
('Вена', 'Vienna', 35),
('Грац', 'Graz', 35),
('Зальцбург', 'Salzburg', 35),
('Линц', 'Linz', 35),
('Инсбрук', 'Innsbruck', 35),
('Берн', 'Bern', 36),
('Цюрих', 'Zurich', 36),
('Женева', 'Geneva', 36),
('Базель', 'Basel', 36),
('Лугано', 'Lugano', 36),
('Минск', 'Minsk', 37),
('Гомель', 'Gomel', 37),
('Могилев', 'Mogilev', 37),
('Витебск', 'Vitebsk', 37),
('Гродно', 'Grodno', 37),
('Киев', 'Kyiv', 38),
('Харьков', 'Kharkiv', 38),
('Одесса', 'Odesa', 38),
('Днепр', 'Dnipro', 38),
('Запорожье', 'Zaporizhzhia', 38),
('Кишинев', 'Chișinău', 39),
('Бельцы', 'Bălți', 39),
('Тирасполь', 'Tiraspol', 39),
('Рыбница', 'Rîbnița', 39),
('Калараш', 'Călărași', 39),
('Нур-Султан', 'Nur-Sultan', 40),
('Алматы', 'Almaty', 40),
('Шымкент', 'Shymkent', 40),
('Актобе', 'Aktobe', 40),
('Караганда', 'Karaganda', 40),
('Ташкент', 'Tashkent', 41),
('Самарканд', 'Samarkand', 41),
('Бухара', 'Bukhara', 41),
('Андижан', 'Andijan', 41),
('Навои', 'Navoi', 41),
('Душанбе', 'Dushanbe', 42),
('Хорог', 'Khorog', 42),
('Кулоб', 'Kulob', 42),
('Истаравшан', 'Istaravshan', 42),
('Рудаки', 'Rudaki', 42),
('Бишкек', 'Bishkek', 43),
('Ош', 'Osh', 43),
('Талас', 'Talas', 43),
('Нарын', 'Naryn', 43),
('Чолпон-Ата', 'Cholpon-Ata', 43),
('Тбилиси', 'Tbilisi', 44),
('Батуми', 'Batumi', 44),
('Кутаиси', 'Kutaisi', 44),
('Зугдиди', 'Zugdidi', 44),
('Рустави', 'Rustavi', 44),
('Ереван', 'Yerevan', 45),
('Гюмри', 'Gyumri', 45),
('Ванадзор', 'Vanadzor', 45),
('Раздан', 'Razdan', 45),
('Армавир', 'Armavir', 45),
('Баку', 'Baku', 46),
('Гянджа', 'Ganja', 46),
('Сумгаит', 'Sumgayit', 46),
('Ленкорань', 'Lankaran', 46),
('Ширван', 'Şirvan', 46),
('Дамаск', 'Damascus', 47),
('Алеппо', 'Aleppo', 47),
('Хомс', 'Homs', 47),
('Латакия', 'Latakia', 47),
('Тартус', 'Tartus', 47),
('Багдад', 'Baghdad', 48),
('Мосул', 'Mosul', 48),
('Басра', 'Basra', 48),
('Киркук', 'Kirkuk', 48),
('Наджаф', 'Najaf', 48),
('Тегеран', 'Tehran', 49),
('Исфахан', 'Isfahan', 49),
('Шираз', 'Shiraz', 49),
('Тебриз', 'Tabriz', 49),
('Машхад', 'Mashhad', 49),
('Иерусалим', 'Jerusalem', 50),
('Тель-Авив', 'Tel Aviv', 50),
('Хайфа', 'Haifa', 50),
('Беэр-Шева', 'Beersheba', 50),
('Назарет', 'Nazareth', 50);
