apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
         - name: PROJECT
           image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
           ports:
             - containerPort: PORT_CONTAINER

           env:
             - name: PROD_DOMAIN
               valueFrom:
                 secretKeyRef:
                   name: storage-backend-production-config-secret
                   key: PROD_DOMAIN
             - name: DATABASE_URL
               valueFrom:
                 secretKeyRef:
                   name: storage-backend-production-config-secret
                   key: DATABASE_URL
             - name: S3_REGION
               valueFrom:
                 secretKeyRef:
                   name: storage-backend-production-config-secret
                   key: S3_REGION
             - name: S3_ENDPOINT
               valueFrom:
                 secretKeyRef:
                   name: storage-backend-production-config-secret
                   key: S3_ENDPOINT
             - name: S3_KEY_ID
               valueFrom:
                 secretKeyRef:
                   name: storage-backend-production-config-secret
                   key: S3_KEY_ID
             - name: S3_KEY_SECRET
               valueFrom:
                 secretKeyRef:
                   name: storage-backend-production-config-secret
                   key: S3_KEY_SECRET
             - name: S3_PATH
               valueFrom:
                 secretKeyRef:
                   name: storage-backend-production-config-secret
                   key: S3_PATH
             - name: BUCKET_NAME
               valueFrom:
                 secretKeyRef:
                   name: storage-backend-production-config-secret
                   key: BUCKET_NAME
             - name: API_PREFIX
               valueFrom:
                 secretKeyRef:
                   name: storage-backend-production-config-secret
                   key: API_PREFIX
